# Generated by Django 6.0.7 on 2026-07-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_collection_created_at_collection_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='Image de couverture'),
        ),
    ]
