# Generated by Django 6.0.7 on 2026-08-10 22:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_reference', models.CharField(blank=True, help_text='ID de la transaction généré par le prestataire de paiement', max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant exact tenté lors de cette transaction', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESSFUL', 'Réussie'), ('FAILED', 'Échouée'), ('CANCELED', 'Annulée')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('STRIPE', 'Stripe'), ('CINETPAY', 'CinetPay'), ('WAVE', 'Wave'), ('OMCIV2', 'Orange Ci'), ('FLOOZ', 'Moov Ci'), ('MOMOCI', 'Mtn Ci'), ('OMBF', 'Orange Bf'), ('OMML', 'Orange Mali'), ('MOMOBJ', 'Mtn Benin'), ('CARD', 'Visa Mastercard'), ('FLOOZBJ', 'Moov Benin'), ('AIRTELNG', 'Airtel Niger'), ('WAVECI', 'Wave Ci'), ('OMSN', 'Orange Senegal'), ('OMGN', 'Orange Guinee Bissau'), ('OMCM', 'Orange Cameroun'), ('WAVESN', 'Wave Senegal'), ('MOOTG', 'Flooz Togo'), ('TOGOCEL', 'Togo Cel'), ('MOMOCM', 'Mtn Cameroun'), ('PAYPAL', 'PayPal'), ('SIMULATED', 'Simulation')], default='STRIPE', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur renvoyé par la banque en cas d'échec", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='order.order')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
